sjdddd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: gym-management
    username: root
    password: guess@lb1221LB

  alioss:
    access-key-id:
    access-key-secret:
    bucket-name:
    endpoint:
